POST http://localhost:5353/users
Content-Type: application/json

{
  "firstname": "gilbert",
  "lastname": "montagné",
  "email": "g.montagne@api.fr",
  "password": "password",
  "repeated_password":"password"
}

###

GET http://localhost:5353/users?orderBy=email&direction=asc&limit=10

###

POST http://localhost:5353/token
Content-Type: application/json

{
  "email": "g.montagne@api.fr",
  "password": "password"
}